CREATE DATABASE IF NOT EXISTS Rounds;

USE Rounds; 

CREATE TABLE Rounds(
roundID int PRIMARY KEY AUTO_INCREMENT,
gameID int NOT NULL,
roundNumber int NOT NULL, 
guess CHAR(4) NOT NULL,
results VARCHAR(12) NOT NULL  
);

