CREATE DATABASE IF NOT EXISTS Round;

USE Round; 

CREATE TABLE Round(
roundID int PRIMARY KEY AUTO_INCREMENT,
gameID int NOT NULL,
roundNumber int NOT NULL, 
guess CHAR(4) NOT NULL,
result VARCHAR(12) NOT NULL  
);


